### ISSUE TITLE
build-ami fails with 'you must have a tty to run sudo'

### ISSUE THREAD

**Issue by ben-roling** [cloudera/director-scripts#2]
On my first attempt with the build-ami script I got a failure with 'you must have a tty to run sudo':

```
preloaded-ami-builder (master)]$ sh build-ami.sh us-east-1 ami-26cc934e "Test CDH packer"
Found packer version: Packer v0.8.6
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 5653626a-b967-d8dd-059c-9d05ebe1aef8
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-c36a7774
==> amazon-ebs: Waiting for instance (i-c36a7774) to become ready...
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Provisioning with shell script: /var/folders/9k/wlyxzx3d4mb2kx3jkdk9t9t56bkgvq/T/packer-shell523778794
    amazon-ebs: sudo: sorry, you must have a tty to run sudo
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: No AMIs to cleanup
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 1
```

It looks to me like all that needs to be done to fix is to add ssh_pty: true to the builders block of packer json file.

Some more information can be found here:
http://stackoverflow.com/questions/31788902/packer-build-fails-due-to-tty-needed-for-sudo

I will post a PR with the change.

**Comment by ben-roling** [comment]
Just to clarify, I have tested the change in the PR and was able to successfully build an AMI.

**Comment by bhavanki** [comment]
Thanks for the heads-up! Your change is in the repository as of May, as part of other improvements.

We've only recently changed our process for taking in changes from outside Cloudera, so that we can simply accept PRs here and bring them back to our internal repo. Future issues and PRs should be resolved in a better fashion, especially for preserving credit and for proper tracking.

Thanks again!
