### ISSUE TITLE
Update Cloudera Documentation with scripts that have been moved in this repository 

### ISSUE THREAD

**Issue by sdavids13** [cloudera/director-scripts#33]
The [Cloudera Documentation](https://www.cloudera.com/documentation/enterprise/latest/topics/admin_hive_etl_jobs_on_s3.html#prepare_cdh_amis)  is pointing to an old directory in this repository with regard to creating preloaded AMIs, I believe those scripts have moved to the `faster-bootstrap` directory.

**Comment by bhavanki** [comment]
Thanks for pointing this out @sdavids13 ! It looks like the doc page is out of date, so we'll work on getting it corrected. You are right that the scripts have moved to faster-bootstrap.

Also, the MANAGES_PARCELS flag listed in the doc isn't needed with the more recent versions of Cloudera Manager; just follow the steps in https://github.com/cloudera/director-scripts/blob/master/faster-bootstrap/ami-usage.md to use a preloaded AMI.

**Comment by bhavanki** [comment]
I checked the documentation today and the link has been updated.
