### ISSUE TITLE
Confusing comment for cdsw installation

### ISSUE THREAD

**Issue by TobyHFerguson** [cloudera/director-scripts#36]
`config/aws.cdsw.conf`

What does this comment mean exactly:

> # To successfully bootstrap a cluster with director, also change the flag
> # "lp.normalization.mountAllUnmountedDisksRequired = false" in server application.properties.
> 

Does this mean 'set the flag to false', or change it to something other than false?

And where is 'application.properties' - I *think* this is on the director machine - if so, why not give the full path (or at least state that that's the machine this file is on!)

**Comment by handavid** [comment]
We will clarify this language.
This issue refers to https://github.com/cloudera/director-scripts/blob/master/configs/aws.cdsw.conf#L12

In the meantime, please refer to the documentation for more information
https://www.cloudera.com/documentation/director/latest/topics/director_cdsw_install.html

**Comment by bhavanki** [comment]
Fixed in commit 27325f6a94f6fbda4658017d2582e1cec10f73d4.
