### ISSUE TITLE
faster-bootstrap/scripts/service_control.sh - should implement stop

### ISSUE THREAD

**Issue by TobyHFerguson** [cloudera/director-scripts#37]
the `rhel_provisioner.sh` calls `service_control firewalld stop`, but `stop` isn't recognized. It should be implemented.

**Comment by handavid** [comment]
Thanks! We'll investigate and fix this.

**Comment by bhavanki** [comment]
Fixed with fbf11f225a87e5bccd5f88eecc6064aa2eb5c0e3
