### ISSUE TITLE
"Unknown configuration key `ssh_private_ip`" error thrown by packer v1.2<

### ISSUE THREAD

**Issue by balazsgaspar** [cloudera/director-scripts#40]
When running the faster-boostrap tool with packer 1.2.0 and above, packer throws following error during validating the `rhel.json` configuration:
```
unknown configuration key: "ssh_private_ip"
```

This is due to changes made in packer 1.2 described in the discussions below:
hashicorp/packer#5680
hashicorp/packer#5630

**Comment by bhavanki** [comment]
This was fixed back in the summer of 2018.
